### ISSUE TITLE
how to install npm packages globally

### ISSUE THREAD

**Issue by samatkiss** [jefferyb/code-server-openshift#1]
Hi,

i need to install npm packages globally ( like jshint) i need root, but i cant switch to root from user...

could you help me?

**Comment by jefferyb** [comment]
Hi @samatkiss,
You can either create a new image with your packages or you can create a bash file called `setup-vscode` and depending on how you're running in it, you can mount it to `/home/coder/projects/.setup/setup-vscode` and it will get executed every time the container (re)starts

For example, using Docker:

setup-vscode file:
```
#!/bin/bash

# install jshint
npm install jshint
```

```
$ chmod +x setup-vscode
$ docker run -itd --name code-server -e CODER_PASSWORD=welcome2vscode -p 9000:9000 -v "${PWD}:/home/coder/project" -v ./setup-vscode: /home/coder/projects/.setup/setup-vscode jefferyb/code-server
```
and that should install jshint and ready for anyone who wants to use it at http://localhost:9000
I hope that helps,
-Jeffery
